# Generated by Django 6.0.6 on 2026-06-30 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Buyurtma summasidan oladigan foizi (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Kunlik ish haqi (UZS)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Oylik ish haqi (UZS)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.role'),
        ),
    ]
