# Generated by Django 6.0.6 on 2026-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_transaction_smena'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_voided',
            field=models.BooleanField(
                default=False,
                help_text="Buyurtma o'chirilgani sababli bekor qilingan tranzaksiya — balansdan ayirilgan, "
                          "lekin tarix uchun saqlanadi",
            ),
        ),
    ]
