# Generated by Django 6.0.6 on 2026-06-25 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopiq')], default='open', max_length=10)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Smena',
                'verbose_name_plural': 'Smenalar',
                'ordering': ['-opened_at'],
            },
        ),
    ]
