# Generated by Django 6.0.6 on 2026-06-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', "Bo'sh"), ('busy', 'Band')], default='free', max_length=20),
        ),
    ]
