# Generated by Django 6.0.6 on 2026-06-30 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_commission_percent_and_more'),
        ('orders', '0006_remove_is_modified_sent_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_takeaway',
            field=models.BooleanField(default=False, help_text="Mijoz o'zi kelib oldi (saboy) — bu holatda xodimga komissiya hisoblanmaydi", verbose_name='Saboy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
