# Generated by Django 6.0.6 on 2026-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text="Buyurtma admin tomonidan o'chirilgan vaqt (agar o'chirilgan bo'lsa)",
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('open', 'Ochiq'), ('closed', 'Yopiq'), ('cancelled', 'Bekor'), ('deleted', "O'chirilgan")],
                default='open', max_length=20,
            ),
        ),
    ]
