# Generated by Django 6.0.6 on 2026-07-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_deleted_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopiq'), ('cancelled', 'Bekor'), ('deleted', "O'chirilgan")], db_index=True, default='open', max_length=20),
        ),
    ]
