# Generated by Django 5.1.15 on 2026-07-09 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sync_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_dirty',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_dirty',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
