# Generated by Django 5.1.15 on 2026-07-09 07:40
# Patched: sync_id backfill split into separate steps to avoid
# UNIQUE constraint collisions on SQLite when multiple rows already exist.

import uuid
from django.db import migrations, models


def populate_sync_ids(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    for obj in Order.objects.all():
        obj.sync_id = uuid.uuid4()
        obj.save(update_fields=['sync_id'])
    for obj in OrderItem.objects.all():
        obj.sync_id = uuid.uuid4()
        obj.save(update_fields=['sync_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sync_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_dirty',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_dirty',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.RunPython(populate_sync_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
