# Generated by Django 6.0.6 on 2026-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.CharField(choices=[('58mm', '58mm (kichik termal printer)'), ('80mm', '80mm (standart termal printer)'), ('A4', 'A4 (oddiy printer)'), ('custom', "Boshqa (qo'lda kiritish)")], default='80mm', max_length=20)),
                ('custom_width_mm', models.PositiveIntegerField(default=80, help_text="'Boshqa' tanlanganda chek kengligi (mm)")),
                ('font_size_px', models.PositiveIntegerField(default=13, help_text="Asosiy matn shrift o'lchami (px)")),
                ('print_scale_percent', models.PositiveIntegerField(default=100, help_text="Chop etish masштabi (%) — printer oynasidagi 'Масштаб'га mos")),
                ('auto_print', models.BooleanField(default=True, help_text="To'lov tasdiqlangach chek avtomatik chop etilsin")),
                ('show_logo', models.BooleanField(default=True)),
                ('footer_text', models.CharField(blank=True, default='Xizmatimizdan foydalanganingiz uchun rahmat!\nYana tashrif buyuring', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chek sozlamasi',
                'verbose_name_plural': 'Chek sozlamalari',
            },
        ),
    ]
