# Generated by Django 6.0.6 on 2026-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='pos_grid_columns',
            field=models.PositiveIntegerField(
                default=3,
                help_text="POS (buyurtma) ekranida bir qatorda nechta taom kartasi ko'rsatilsin (3-6)",
                verbose_name='Taomlar panelidagi ustunlar soni',
            ),
        ),
    ]
