# Generated by Django 6.0.6 on 2026-06-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Taomning o'ziga tushgan narxi (UZS) — sof foydani hisoblash uchun", max_digits=12, verbose_name='Tan narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mijozga sotiladigan narx (UZS)', max_digits=12, verbose_name='Sotish narxi'),
        ),
    ]
