# Generated by Django 6.0.6 on 2026-07-01 10:00

from django.db import migrations, models


def set_initial_order(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for idx, product in enumerate(Product.objects.order_by('id')):
        Product.objects.filter(pk=product.pk).update(order=idx)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cost_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(
                default=0,
                help_text="Taomlar ro'yxatida va POS panelida ko'rsatilish tartibi (kichigi birinchi)",
                verbose_name='Tartib raqami',
            ),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.RunPython(set_initial_order, noop),
    ]
