# Generated by Django 5.1.15 on 2026-07-09 07:40
# Patched: sync_id backfill split into separate steps to avoid
# UNIQUE constraint collisions on SQLite when multiple rows already exist.

import uuid
from django.db import migrations, models


def populate_sync_ids(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    for obj in Category.objects.all():
        obj.sync_id = uuid.uuid4()
        obj.save(update_fields=['sync_id'])
    for obj in Product.objects.all():
        obj.sync_id = uuid.uuid4()
        obj.save(update_fields=['sync_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sync_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='sync_dirty',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sync_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sync_dirty',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sync_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.RunPython(populate_sync_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sync_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
